In [1]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None , description: str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
        if description != None :
            print(f" <-- {description} -->")
    print('type: ' , type(val))
    print(val , '\n')
    # return val

In [2]:
import numpy as np # type: ignore
import numpy.typing as npt # type: ignore
import pandas as pd # type: ignore

In [3]:
df = pd.DataFrame([[1,2,3] , [4,5,6] , [7,8,9]] , columns=['A', 'B', 'C'])
pr(df , 'df' , 'display the df that we just created')
pr(df.head() , 'df.head()' , 'the head method make the first five rows visible')
pr(df.head(2) , 'df.head()' , 'i could only look the first two rows by passing a number to head method')

 ---------------------- df ----------------------
 <-- display the df that we just created -->
type:  <class 'pandas.core.frame.DataFrame'>
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

 ---------------------- df.head() ----------------------
 <-- the head method make the first five rows visible -->
type:  <class 'pandas.core.frame.DataFrame'>
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

 ---------------------- df.head() ----------------------
 <-- i could only look the first two rows by passing a number to head method -->
type:  <class 'pandas.core.frame.DataFrame'>
   A  B  C
0  1  2  3
1  4  5  6

In [4]:
pr(df.tail(2) , 'df.tail(2)' , 'i could look to the bottom two rows by passing a number to the tail method')
pr(df.columns , 'df.columns' , 'i could see what are the the headers only')
pr(df.index , 'df.index' , 'i could also see what the index are by calling the index property')
pr(df.index.to_list() , 'df.index.to_list()' , 'you could transform the index from "pandas.core.indexes.range.RangeIndex" object to normal python array ')

 ---------------------- df.tail(2) ----------------------
 <-- i could look to the bottom two rows by passing a number to the tail method -->
type:  <class 'pandas.core.frame.DataFrame'>
   A  B  C
1  4  5  6
2  7  8  9

 ---------------------- df.columns ----------------------
 <-- i could see what are the the headers only -->
type:  <class 'pandas.core.indexes.base.Index'>
Index(['A', 'B', 'C'], dtype='object')

 ---------------------- df.index ----------------------
 <-- i could also see what the index are by calling the index property -->
type:  <class 'pandas.core.indexes.range.RangeIndex'>
RangeIndex(start=0, stop=3, step=1)

 ---------------------- df.index.to_list() ----------------------
 <-- you could transform the index from "pandas.core.indexes.range.RangeIndex" object to normal python array  -->
type:  <class 'list'>
[0, 1, 2]

In [5]:
df = pd.DataFrame([[1,2,3] , [4,5,6] , [7,8,9]] , columns=['A', 'B', 'C'] , index=['X' , 'Y' , 'Z'])
pr(df , 'df' , 'i could change the index from the default auto increment to a custom index')
pr(df.index.to_list , 'df.index.to_list' , 'the new index we just added' )

 ---------------------- df ----------------------
 <-- i could change the index from the default auto increment to a custom index -->
type:  <class 'pandas.core.frame.DataFrame'>
   A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

 ---------------------- df.index.to_list ----------------------
 <-- the new index we just added -->
type:  <class 'method'>
<bound method IndexOpsMixin.tolist of Index(['X', 'Y', 'Z'], dtype='object')>

In [6]:
pr(df.info() , 'df.info()' , 'info method return information about our dataframe')

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, X to Z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes
 ---------------------- df.info() ----------------------
 <-- info method return information about our dataframe -->
type:  <class 'NoneType'>
None

In [7]:
pr(df , 'original frame')
pr(df.describe() , 'df.describe()' , 'describe method return statistical information about our dataframe for each column')

 ---------------------- original frame ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
   A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

 ---------------------- df.describe() ----------------------
 <-- describe method return statistical information about our dataframe for each column -->
type:  <class 'pandas.core.frame.DataFrame'>
         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [8]:
pr(df.nunique() , 'df.nunique()' , 'the unique variables in the dataframe')

 ---------------------- df.nunique() ----------------------
 <-- the unique variables in the dataframe -->
type:  <class 'pandas.core.series.Series'>
A    3
B    3
C    3
dtype: int64

In [9]:
pr(df['A'] , "df['A']" , 'the data in the first column can be accessed like accessing dictionaries with the column name' )

 ---------------------- df['A'] ----------------------
 <-- the data in the first column can be accessed like accessing dictionaries with the column name -->
type:  <class 'pandas.core.series.Series'>
X    1
Y    4
Z    7
Name: A, dtype: int64

In [10]:
pr(df.shape , 'df.shape' , 'shape of the dataframe' )
pr(df.size , 'df.size' , 'size of the dataframe' )

 ---------------------- df.shape ----------------------
 <-- shape of the dataframe -->
type:  <class 'tuple'>
(3, 3)

 ---------------------- df.size ----------------------
 <-- size of the dataframe -->
type:  <class 'int'>
9

In [11]:
grades = pd.DataFrame([
    ['math' , 'math' , 90],
    ['science' , 'science' , 90],
    ['english' , 'english' , 90],
    ] , columns=['name', 'quiz', 'exam'])
pr(grades.head(3), 'grades.head(3)')
pr(grades.columns.to_list(), 'grades.columns.to_list()')
pr(grades.index.to_list(), 'grades.index.to_list()')

 ---------------------- grades.head(3) ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
      name     quiz  exam
0     math     math    90
1  science  science    90
2  english  english    90

 ---------------------- grades.columns.to_list() ----------------------
type:  <class 'list'>
['name', 'quiz', 'exam']

 ---------------------- grades.index.to_list() ----------------------
type:  <class 'list'>
[0, 1, 2]

In [12]:
grades = pd.DataFrame([
    ['math' , 'math' , 90],
    ['science' , 'science' , 90],
    ['english' , 'english' , 90],
    ] , columns=['name', 'quiz', 'exam'] , 
    index = ['s1' , 's2' , 's3'])
pr(grades , 'grades')
pr(grades['exam'] , "grades['exam']")

 ---------------------- grades ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
       name     quiz  exam
s1     math     math    90
s2  science  science    90
s3  english  english    90

 ---------------------- grades['exam'] ----------------------
type:  <class 'pandas.core.series.Series'>
s1    90
s2    90
s3    90
Name: exam, dtype: int64

In [13]:
grades.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, s1 to s3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   quiz    3 non-null      object
 2   exam    3 non-null      int64
dtypes: int64(1), object(2)
memory usage: 96.0+ bytes

In [14]:
grades.describe()

       exam
count   3.0
mean   90.0
std     0.0
min    90.0
25%    90.0
50%    90.0
75%    90.0
max    90.0

In [15]:
grades.describe(include='all')

        name  quiz  exam
count      3     3   3.0
unique     3     3   NaN
top     math  math   NaN
freq       1     1   NaN
mean     NaN   NaN  90.0
std      NaN   NaN   0.0
min      NaN   NaN  90.0
25%      NaN   NaN  90.0
50%      NaN   NaN  90.0
75%      NaN   NaN  90.0
max      NaN   NaN  90.0

In [16]:
pr(grades.shape , 'grades.shape')
pr(grades.size , 'grades.size')

 ---------------------- grades.shape ----------------------
type:  <class 'tuple'>
(3, 3)

 ---------------------- grades.size ----------------------
type:  <class 'int'>
9

In [17]:
grades.nunique

<bound method DataFrame.nunique of        name     quiz  exam
s1     math     math    90
s2  science  science    90
s3  english  english    90>

# Loading in DataFrames from Files (CSV, Excel, Parquet, etc.)

In [18]:
coffee = pd.read_csv('./warmup-data/coffee.csv')
pr(coffee, 'coffee')
pr(coffee.head(), 'coffee.head()')

 ---------------------- coffee ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

 ---------------------- coffee.head() ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [19]:
# there other formats other than csv that have smaller size for the same dataset in comparison with csv. 
results = pd.read_parquet('./data/results.parquet')
# pr(results.head() , 'results.head()')
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [20]:
results_excel = pd.read_excel('./data/olympics-data.xlsx' , sheet_name='results')
results_excel.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [21]:
bios= pd.read_csv('./data/bios.csv')
pr(bios.head(), 'bios.head()')

 ---------------------- bios.head() ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
   athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux
1           2         Arnaud Boetsch  1969-04-01       Meulan
2           3           Jean Borotra  1898-08-13     Biarritz
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe
4           5           Albert Canet  1878-04-17   Wandsworth

            born_region born_country     NOC  height_cm  weight_kg   died_date
0               Gironde          FRA  France        NaN        NaN  1960-10-02
1              Yvelines          FRA  France      183.0       76.0         NaN
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17
3                 Paris          FRA  France      168.0       64.0  1978-03-20
4               England          GBR  France        NaN        NaN  1930-07-25

In [22]:
use_cols : list[str] = ["Day","Coffee Type","Units Sold"] 
dtype_map :dict[str, str] = {"Day":"string" , "Coffee Type" : 'string' , 'Units Sold' : 'Int64'}
coffee = pd.read_csv(
    './warmup-data/coffee.csv' , 
    usecols=use_cols , 
    dtype=dtype_map ,
    encoding='utf-8' ,
    na_values=["" , 'NA']
    )
pr(coffee.head(), 'coffee.head()')
pr(coffee.dtypes , 'coffee.dtypes')

 ---------------------- coffee.head() ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

 ---------------------- coffee.dtypes ----------------------
type:  <class 'pandas.core.series.Series'>
Day            string[python]
Coffee Type    string[python]
Units Sold              Int64
dtype: object

# Accessing data with pandas

In [23]:
pr(coffee.head() , 'coffee.head()')
pr(coffee.tail() , 'coffee.tail()')
pr(coffee.sample(5) , 'coffee.sample(5)')

 ---------------------- coffee.head() ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

 ---------------------- coffee.tail() ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

 ---------------------- coffee.sample(5) ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
11   Saturday       Latte          35
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35

In [24]:
pr(coffee.head() , 'coffee.head()')
pr(coffee.loc[0] , 'coffee.loc[0]')
pr(coffee.loc[0 , 'Day'] , 'coffee.loc[0 , Day]')

 ---------------------- coffee.head() ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

 ---------------------- coffee.loc[0] ----------------------
type:  <class 'pandas.core.series.Series'>
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

 ---------------------- coffee.loc[0 , Day] ----------------------
type:  <class 'str'>
Monday

In [25]:
pr(coffee.loc[0:3 , ['Day' , 'Units Sold']] )
pr(coffee.iloc[0:3 , [0,2]] )

type:  <class 'pandas.core.frame.DataFrame'>
       Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30
3  Tuesday          20

type:  <class 'pandas.core.frame.DataFrame'>
       Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30

In [26]:
# we could change the index from numerical values to string values from the Days column
coffee.index = coffee['Day']
pr(coffee.head() , 'coffee.head()')
pr(coffee.loc[['Monday'] , ['Coffee Type' , 'Units Sold']])

 ---------------------- coffee.head() ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

type:  <class 'pandas.core.frame.DataFrame'>
       Coffee Type  Units Sold
Day
Monday    Espresso          25
Monday       Latte          15

In [27]:
coffee = pd.read_csv('./warmup-data/coffee.csv')
pr(coffee.head() , 'coffee.head()')
# we could change any value in the dataframe
coffee.loc[1, 'Units Sold'] = 10
pr(coffee.head() , 'coffee.head()')
# we could even set multiple values
coffee.loc[2:4 , 'Units Sold'] = 1
pr(coffee.head() , 'coffee.head()')

 ---------------------- coffee.head() ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

 ---------------------- coffee.head() ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

 ---------------------- coffee.head() ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso           1
3    Tuesday       Latte           1
4  Wednesday    Espresso           1

In [28]:
# we could access a specific column in two ways 
pr(coffee.Day , 'coffee.Day')
pr(coffee['Day'] , 'coffee[Day]')

 ---------------------- coffee.Day ----------------------
type:  <class 'pandas.core.series.Series'>
0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

 ---------------------- coffee[Day] ----------------------
type:  <class 'pandas.core.series.Series'>
0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [29]:
# we can sort data with specific column
pr(coffee.sort_values(['Units Sold' , 'Coffee Type'] , ascending=False) , 'coffee.sort_values')

 ---------------------- coffee.sort_values ----------------------
type:  <class 'pandas.core.frame.DataFrame'>
          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
5   Wednesday       Latte          25
0      Monday    Espresso          25
1      Monday       Latte          10
3     Tuesday       Latte           1
2     Tuesday    Espresso           1
4   Wednesday    Espresso           1

In [30]:
# for some really rare events you could use for loops
for index, row in coffee.iterrows():
    print('## row:')
    print(row)
    print('## index: ', index)
    print('--------------------------')

## row:
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object
## index:  0
--------------------------
## row:
Day            Monday
Coffee Type     Latte
Units Sold         10
Name: 1, dtype: object
## index:  1
--------------------------
## row:
Day             Tuesday
Coffee Type    Espresso
Units Sold            1
Name: 2, dtype: object
## index:  2
--------------------------
## row:
Day            Tuesday
Coffee Type      Latte
Units Sold           1
Name: 3, dtype: object
## index:  3
--------------------------
## row:
Day            Wednesday
Coffee Type     Espresso
Units Sold             1
Name: 4, dtype: object
## index:  4
--------------------------
## row:
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object
## index:  5
--------------------------
## row:
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object
## index:  6
--------------------------
## row:
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object
## index:  7
--------------------------
## row:
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object
## index:  8
--------------------------
## row:
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object
## index:  9
--------------------------
## row:
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object
## index:  10
--------------------------
## row:
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object
## index:  11
--------------------------
## row:
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object
## index:  12
--------------------------
## row:
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object
## index:  13
--------------------------

# Filtering data

In [32]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [ ]:
# the filtering syntax used below with the loc is very different and strange for me. please explain it.
# what really make me very confused that this `bios['height_cm'] > 220` code should evaluate to True or False
# this is like saying `bios.loc[True]` which don't make sense and don't work.
bios.loc[bios['height_cm'] > 220]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN

In [36]:
# you could even pick specific columns with this syntax
bios.loc[bios['height_cm'] > 220 , ['name' , 'born_country' , 'height_cm']]

                   name born_country  height_cm
5673     Gunther Behnke          GER      221.0
5781     Tommy Burleson          USA      223.0
6978    Arvydas Sabonis          LTU      223.0
89070          Yao Ming          CHN      226.0
89075    Roberto Dueñas          ESP      221.0
120266     Zhang Zhaoxu          CHN      221.0

In [41]:
# here's another way to basically achieve the same result.
bios[bios['height_cm'] > 220][['name' , 'born_country' , 'height_cm']]

                   name born_country  height_cm
5673     Gunther Behnke          GER      221.0
5781     Tommy Burleson          USA      223.0
6978    Arvydas Sabonis          LTU      223.0
89070          Yao Ming          CHN      226.0
89075    Roberto Dueñas          ESP      221.0
120266     Zhang Zhaoxu          CHN      221.0

In [ ]:
# we can also combine more than one condition
# There are another confusion point when using the & operator. i tried to use the `and` key word which work for boolean operation but don't work here. could you explain the difference between the `and` key word and the `&` operator and when to use each.
bios[(bios['height_cm']> 215) & (bios['born_country'] == 'USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [50]:
mask = bios['height_cm'] > 220 
pr(mask.head() , 'mask.head')
bios.loc[mask , ['name' , 'born_country' , 'height_cm']]

 ---------------------- mask.head ----------------------
type:  <class 'pandas.core.series.Series'>
0    False
1    False
2    False
3    False
4    False
Name: height_cm, dtype: bool

                   name born_country  height_cm
5673     Gunther Behnke          GER      221.0
5781     Tommy Burleson          USA      223.0
6978    Arvydas Sabonis          LTU      223.0
89070          Yao Ming          CHN      226.0
89075    Roberto Dueñas          ESP      221.0
120266     Zhang Zhaoxu          CHN      221.0